name: Zip All Files
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Generate ZIP
        uses: MineAndDine96/MC-Litematics@main
        with:
          filename: 'litematics.zip'
